import { AppConfig } from "./types";

export const APP_CONFIG: AppConfig = {
	appName: "NeuroScan AI",
	appSubtitle: "Medical Imaging",
	navItems: [
		{ to: "/", icon: "LayoutDashboard", label: "Dashboard" },
		{ to: "/upload", icon: "Upload", label: "Upload Scan" },
		{ to: "/scans", icon: "Images", label: "Scan Library" },
		{ to: "/reports", icon: "FileText", label: "Reports" },
		{ to: "/settings", icon: "Settings", label: "Settings" },
	],
	dashboard: {
		welcomeMessage: "Welcome back, {userName}. Here's your imaging overview.",
		newScanButtonLabel: "New Scan",
		recentScansTitle: "Recent Scans",
		viewAllLabel: "View All",
		searchPlaceholder: "Search scans, patients...",
	},
	scanLibrary: {
		title: "Scan Library",
		subtitle: "Browse and manage all processed MRI scans.",
		searchPlaceholder: "Search by name or ID...",
		noScansFound: "No scans found",
		adjustFilters: "Try adjusting your search or filters.",
	},
	volumeChart: {
		title: "Tumour Volume Distribution",
		subtitle: "Segmentation volumes (cm³) across flagged scans",
	},
	upload: {
		title: "Upload MRI Scan",
		subtitle:
			"Upload MRI files for AI-powered tumour detection, classification, and segmentation.",
		backButton: "Back",
	},
	reports: {
		title: "Reports",
		subtitle: "View and download AI analysis reports for completed scans.",
		exportAll: "Export All",
		searchPlaceholder: "Search by name or ID...",
		noReportsFound: "No reports found",
		autoGenerated:
			"Reports are generated automatically when scans complete processing.",
	},
	scanDetail: {
		backButton: "Back",
		retryButton: "Retry",
		exportButton: "Export",
		reportButton: "Report",
		viewerTab: "2D Viewer",
		pipelineTab: "Pipeline",
		reportTab: "Report",
		measurementsTitle: "Measurements",
		reportTitle: "AI Analysis Report",
		findingsTitle: "Findings",
		volumetricTitle: "Volumetric Analysis",
		downloadPDF: "Download PDF",
		exportCSV: "Export CSV",
		notAvailable: "Report not available",
		processingRequired:
			"Processing must complete before a report can be generated.",
	},
};
