export type Modality = "FLAIR" | "T1" | "T1CE" | "T2";

export interface ScanResult {
	detected: boolean;
	classification: string;
	confidence: number;
	tumorVolume: number;
	wtVolume: number;
	tcVolume: number;
	etVolume: number;
}

export interface MRIScan {
	id: string;
	patientId: string;
	patientName: string;
	scanDate: string;
	modalities: Modality[];
	progress: number;
	pipelineStep: string;
	status: string;
	results?: ScanResult;
}

export interface AppConfig {
	appName: string;
	appSubtitle: string;
	navItems: {
		to: string;
		icon: string;
		label: string;
	}[];
	dashboard: {
		welcomeMessage: string;
		newScanButtonLabel: string;
		recentScansTitle: string;
		viewAllLabel: string;
		searchPlaceholder: string;
	};
	scanLibrary: {
		title: string;
		subtitle: string;
		searchPlaceholder: string;
		noScansFound: string;
		adjustFilters: string;
	};
	volumeChart: {
		title: string;
		subtitle: string;
	};
	upload: {
		title: string;
		subtitle: string;
		backButton: string;
	};
	reports: {
		title: string;
		subtitle: string;
		exportAll: string;
		searchPlaceholder: string;
		noReportsFound: string;
		autoGenerated: string;
	};
	scanDetail: {
		backButton: string;
		retryButton: string;
		exportButton: string;
		reportButton: string;
		viewerTab: string;
		pipelineTab: string;
		reportTab: string;
		measurementsTitle: string;
		reportTitle: string;
		findingsTitle: string;
		volumetricTitle: string;
		downloadPDF: string;
		exportCSV: string;
		notAvailable: string;
		processingRequired: string;
	};
}

export interface AppStat {
	label: string;
	value: number;
	type: string;
}
